name: edgehead
version: 2.0.0
description: A game of fractal stories.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://www.egamebook.com
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  built_collection: ^4.1.0
  built_value: '>=6.7.0 <8.0.0'
  cli_menu: ^0.2.2
  egamebook_builder:
    path: ../egamebook_builder
  logging: ^0.11.3
  meta: ^1.1.8
  path: ^1.6.2
  quiver: ^2.0.0+1
  slot_machine: ^5.0.1

dev_dependencies:
  args: ^1.5.0
  build_runner: ^1.10.1
  built_value_generator: ^7.1.0
  lint: ^1.3.0
  t_stats: ^2.1.1
  test: ^1.15.3

# As of version 7.1.0, built_value_generator doesn't include analyzer 0.40.0
# in its dependency range. Until that's fixed (with 8.0.0), we need to force
# that version. (The previous version of analyzer had a file system bug.)
dependency_overrides:
  analyzer: 0.40.2
